export const INCREMENT = 'INCREMENT'
export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const FILTER_SET_USERNAME = 'FILTER_SET_USERNAME'
export const FILTER_SET_ARTICLES = 'FILTER_SET_ARTICLES'
export const FILTER_SET_DATES = 'FILTER_SET_DATES'
